#### Librairie et Matrices

In [1]:
import numpy as np

In [2]:
M_np=[[0.8165598, 0.6241732, 0.6240969, 0.6240302],
[0.8597795, 0.6958361, 0.6957673, 0.6957071],
[0.8597966, 0.6958662, 0.6957974, 0.6957372],
[0.8598116, 0.6958925, 0.6958237, 0.6957635]]

#### Approche Classique sous Python

In [3]:
invM_np=np.linalg.inv(M_np)

In [4]:
print(invM_np)

[[-2.63593154e-02  1.48380730e+07 -3.18199022e+07  1.69818292e+07]
 [ 1.39806887e+07  1.08706075e+13 -2.33899397e+13  1.25193167e+13]
 [-2.99584160e+07 -2.34082761e+13  5.03664604e+13 -2.69581511e+13]
 [ 1.59777273e+07  1.25376601e+13 -2.69765026e+13  1.44388248e+13]]


In [5]:
np.dot(M_np,invM_np) # Aie... 

array([[1.        , 0.        , 0.        , 0.        ],
       [0.        , 0.99804688, 0.        , 0.        ],
       [0.        , 0.        , 1.        , 0.        ],
       [0.        , 0.        , 0.00390625, 1.        ]])

## Package mpmath

In [6]:
import mpmath as mp
# Setting precision
mp.mp.dps = 100

In [7]:
M_mp=mp.matrix([[0.8165598, 0.6241732, 0.6240969, 0.6240302],
[0.8597795, 0.6958361, 0.6957673, 0.6957071],
[0.8597966, 0.6958662, 0.6957974, 0.6957372],
[0.8598116, 0.6958925, 0.6958237, 0.6957635]])

In [8]:
invM_mp=M_mp**-1

In [9]:
product=invM_mp * M_mp

#### Precision element de la diagonale

In [10]:
for i in range(4):
    print(product[i,i])

1.000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010650479
1.00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000028711967
0.9999999999999999999999999999999999999999999999999999999999999999999999999999999999999999997377048978
1.000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000155430732


#### Precision des autres elements

In [11]:
for i in range(4):
    for j in range(4):
        if i != j:
            print(product[i,j])

8.621736527706886934737664366805244779207747825843322912821573564068318300785617267934305712618133005e-93
8.620902316480749619471956101251098617126570655953667220524473882162606767618331953020979713266529993e-93
8.620229413991541672127705050719084688813432952093170132892558211795202639565273034060589605247899246e-93
3.813390292853443591479366091193085605867890760098397229143322004839764821199673805499801378353012261e-91
3.005401809752583591433506592708877033003533646612601235555378045969841205526720896542758152385809872e-91
3.537041189168876959909426388393642482925854401724578046989831995448965571235335532117796515247629368e-91
-3.455651953084138688104098549326767603362344065650294503961262365478682206885649149544439152109855686e-91
-2.333596818451385360118737425948414799318639128188048083602022336546806848525955338360538738168267104e-91
-3.768094524746935110300578692511850367756414210379680996975093110769757729149954485251871542140004003e-91
1.27754958853004565259596143096647471099337

### Application de la methode a la sous matrice

In [12]:
sM = mp.matrix([[0.8165598, 0.6241732, 0.6240969],
[0.8597795, 0.6958361, 0.6957673],
[0.8597966, 0.6958662, 0.6957974]])
sM_inv = sM ** -1

In [13]:
product2=sM_inv * sM

In [14]:
for i in range(3):
    print(product2[i,i])

1.000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001862
0.9999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999997707
0.9999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999977968


In [15]:
for i in range(3):
    for j in range(3):
        if i != j:
            print(product[i,j])

8.621736527706886934737664366805244779207747825843322912821573564068318300785617267934305712618133005e-93
8.620902316480749619471956101251098617126570655953667220524473882162606767618331953020979713266529993e-93
3.813390292853443591479366091193085605867890760098397229143322004839764821199673805499801378353012261e-91
3.005401809752583591433506592708877033003533646612601235555378045969841205526720896542758152385809872e-91
-3.455651953084138688104098549326767603362344065650294503961262365478682206885649149544439152109855686e-91
-2.333596818451385360118737425948414799318639128188048083602022336546806848525955338360538738168267104e-91


### Les deux matrices completes

#### Matrice 1 

In [16]:
for i in range(4):
    print('Ligne '+str(i+1))
    for j in range(4):
            print(invM_mp[i,j])
    print('')

Ligne 1
-0.02635771465074259391399365657884570633124795333490538328026294956381620626363025631322274171982087965
14838074.26880921400294104045870975637963656583625953793183555089169759279822268710803920995373240097
-31819904.90105690865944839212585749290791375455105139594953837152509867682357926561456082406387659119
16981830.661478706689254626027955704127902168761707057999999256949235494842869309475129666691819664

Ligne 2
13980689.88851201329437721355797241627989257322241989138593594307920756775913482576044913736101962833
10870608402191.64693885308914531527815080683639657755243825339105427374286742769681591192216404181406
-23389941666419.47728088518059942487025398283470546163854717628210946075057503284661174868813292734914
12519317774015.06153122176939665847402134936085943811815345938598691965360535844121839089724954379238

Ligne 3
-29958418.47679286722247191623922220583830650909829619598311465882547603358366404789846836515329040534
-23408278053592.968604496319984291256395429204563522

### Matrice 2

In [17]:
for i in range(3):
    print('Ligne '+str(i+1))
    for j in range(3):
            print(sM_inv[i,j])
    print('')

Ligne 1
-18.81812662584655651746181337901059361395835410366625388499983269505467333038518215936601515243308589
92246.6488197125496746256803571604159314313707007434379440759975575394481076682631966409040766239985
-92225.77929846904592572117357152559320117301560749119353699367055303150287791407219249460121357083118

Ligne 2
127052.3611529960905498817936151818209439682468387617947528509478328087882060620719074122185030489172
-286820798.5175677069263680063269836722549004219520248879746221324441475502319503242529752474300401376
286694430.8554168372955323307697741009540101719895109339818339449333298894223797540728164822441724466

Ligne 3
-127041.6704564744468167700935773508275140381135868340813960080977252258030076845099125599799617955431
286735170.0227234031881365702315821146409755234038484127829921581063597353096408378724052776091708321
-286608814.2166792864928450123778723272597512535230143467608367730453993239815535453446038861552780611

