In [44]:
import numpy as np 
import numpy.linalg as lin
import time

### General Case

In [3]:
A = np.array([[1,2],[3,4]]) ; B=lin.inv(A)

In [14]:
print(A)

[[1 2]
 [3 4]]


In [15]:
print(B)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [16]:
C = np.matmul(A,B)

In [17]:
print(C) # Du au float

[[1.00000000e+00 1.11022302e-16]
 [0.00000000e+00 1.00000000e+00]]


In [22]:
C_approx = np.round(C,3)

In [23]:
print(C_approx)

[[1. 0.]
 [0. 1.]]


In [24]:
# Python fait les produits d'array element-wise pour la multiplication par *
A*B

array([[-2. ,  2. ],
       [ 4.5, -2. ]])

### Near Singular Matrix

In [30]:
def hilbert(size):
    """ Hilbert Matrix - Approche un peu par force brute"""
    hilb=np.zeros((size,size))
    for i in range(size):
        for j in range(size):
            hilb[i,j]=1/(i+j+1)
    return hilb

In [41]:
H = hilbert(5)
print(H)

[[1.         0.5        0.33333333 0.25       0.2       ]
 [0.5        0.33333333 0.25       0.2        0.16666667]
 [0.33333333 0.25       0.2        0.16666667 0.14285714]
 [0.25       0.2        0.16666667 0.14285714 0.125     ]
 [0.2        0.16666667 0.14285714 0.125      0.11111111]]


In [42]:
cond_num = lin.cond(H) # ill-conditionned matrix
print(cond_num)

476607.25024100044


In [54]:
H_new = hilbert(5000)
cond_num_new = lin.cond(H_new)
print(cond_num_new)

4.579608423253534e+22


In [55]:
start_time=time.time()

H_new_inv = lin.inv(H_new)

end_time=time.time()

In [56]:
print('Time to invert:',end_time-start_time)

Time to invert: 4.002329349517822


In [57]:
print(H_new_inv)

[[ 1.43092575e+02 -9.77844292e+03  2.03071780e+05 ...  1.58348837e+09
   3.79263554e+09 -5.54636828e+08]
 [-9.71672832e+03  8.37841073e+05 -1.77189161e+07 ... -2.71984866e+11
  -6.60213130e+11  8.21945551e+10]
 [ 1.94606568e+05 -1.67822102e+07  2.85202135e+08 ...  1.13431268e+13
   2.81820411e+13 -2.98079695e+12]
 ...
 [-1.00199871e+09  1.80487828e+11 -7.96224436e+12 ... -1.01738563e+17
   1.80903075e+17 -1.53787961e+17]
 [-2.46274159e+09  4.37294664e+11 -1.90422396e+13 ... -1.25333740e+16
   5.10023166e+17  9.53188958e+16]
 [-2.85405593e+09  5.14081200e+11 -2.27087658e+13 ... -3.33918745e+17
  -2.51011611e+16  5.85354825e+15]]
